### ISSUE TITLE
DSPipelines operator Pods should have better labels

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#140]
Description of problem:

When looking at the data-science-pipelines-operator-controller-manager Deployment, I see that its Pods have only one label control-plane: controller-manager:

```yaml
kind: Deployment
metadata:
  name: data-science-pipelines-operator-controller-manager
  namespace: redhat-ods-applications
spec:
  ...
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
```

the pods should have a more accurate label, specifying which service it's providing, and not a generic one like "control-plane: controller-manager".

Disclaimer: this was reverted because it failed to upgrade, ensure that when we add this back in we account for a seamless upgrade.
