### ISSUE TITLE
Write Contributing/Testing process documentation

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#159]
Write a document that specifies the standard testing/deployment procedure **for developers**.  The spirit behind this issue is that there are multiple competing ways to deploy and/or test out a PR changeset (publish a container image, `make deploy`, apply YAMLs directly, etc), and it is unclear for reviewers exactly which procedure to follow.

**Comment by gmfrasca** [comment]
(responding to @HumairAK's question and/or providing context for this ticket):

I think the best way do this is create either a new section in the README.md, or likely better, create a new CONTRIBUTING.md.

The major points I think we'd like to address are:

- how to run DSPO locally
- how to deploy DSPO as a developer
- how to run unit/functional tests from command line

**Comment by gmfrasca** [comment]
Given that, I think the way we want to standardize is via `make`, as we can:

- deploy to a cluster you are oc-login'd to via `make deploy`/`make undeploy`
- run tests `via make test`, `make unittest`, and `make functest`.
- generate manifests via `make generate` and/or `make manifests`

And finally, running locally can be done via go `run main.go --config=$configfile`, with a config file looking like

```yaml
Images:
  ApiServer: quay.io/opendatahub/ds-pipelines-api-server:main-0e8a011
  Artifact: quay.io/opendatahub/ds-pipelines-artifact-manager:main-0e8a011
  OAuthProxy: registry.redhat.io/openshift4/ose-oauth-proxy:v4.12.0
  PersistentAgent: quay.io/opendatahub/ds-pipelines-persistenceagent:main-0e8a011
  ScheduledWorkflow: quay.io/opendatahub/ds-pipelines-scheduledworkflow:main-0e8a011
  Cache: registry.access.redhat.com/ubi8/ubi-minimal
  MoveResultsImage: registry.access.redhat.com/ubi8/ubi-micro
  MariaDB: registry.redhat.io/rhel8/mariadb-103:1-188
  MlmdEnvoy: quay.io/opendatahub/ds-pipelines-metadata-envoy:1.7.0
  MlmdGRPC: quay.io/opendatahub/ds-pipelines-metadata-grpc:1.0.0
  MlmdWriter: quay.io/opendatahub/ds-pipelines-metadata-writer:1.1.0
  CRDViewer: gcr.io/ml-pipeline/viewer-crd-controller:2.0.0-rc.2
  VisualizationServer: gcr.io/ml-pipeline/visualization-server:2.0.0-rc.2
```
(basically, adapt/expand the variables found in [config/configmaps/files/config.yaml](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/configmaps/files/config.yaml) )

So this task should just be surrounding those utilities with metadata and context such that a new developer can easily get setup and contribute to the project in a self-service manner
