### ISSUE TITLE
Persistence agent fails to connect to ml pipeline API server 

### ISSUE THREAD

**Issue by eyalcha** [opendatahub-io/data-science-pipelines-operator#211]
Deploying Data Science Pipeline with an operator results this error:

```
W0724 06:41:55.550968       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-07-24T06:44:18Z" level=fatal msg="Error creating ML pipeline API Server client: Failed to initialize pipeline client. Error: Waiting for ml pipeline API server failed after all attempts.: Get \"http://ds-pipeline-sample:8888/apis/v1beta1/healthz\": dial tcp 172.21.11.146:8888: connect: connection refused: Waiting for ml pipeline API server failed after all attempts.: Get \"http://ds-pipeline-sample:8888/apis/v1beta1/healthz\": dial tcp 172.21.11.146:8888: connect: connection refused"
```

The ds-pipeline fails with liveness probe issue

<img width="1226" alt="image" src="https://github.com/opendatahub-io/data-science-pipelines-operator/assets/64679987/c83c5444-8390-4633-a037-be0eb5ecf425">

**Comment by gregsheremeta** [comment]
> Deploying Data Science Pipeline with an operator

We'll need some more information. Which operator? It would be best if you could post the exact steps to reproduce -- cluster version, what operator you're using, which version, all steps taken ... thanks!

**Comment by eyalcha** [comment]
@gregsheremeta 

Adding to above, when I tried to install with the following repos, the deployment have succeeded

```
  repos:
    - name: manifests
      uri: https://github.com/opendatahub-io/odh-manifests/tarball/v1.7
    - name: kserve-manifests
      uri: https://github.com/opendatahub-io/odh-manifests/tarball/v1.8
```

I used 1.8 for KServe as it doesn't exists in 1.7
