### ISSUE TITLE
[Feature Request]: Default objectStorage.minio.image value

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/data-science-pipelines-operator#271]
### Feature description

Currently, the DSPA provides an option to have DSPA deploy a minio instance using the following YAML:

```yaml
  objectStorage:
    minio:
      bucket: data-science-pipelines
      deploy: true
      image: quay.io/minio/minio:RELEASE.2023-06-19T19-52-50Z
      pvcSize: 10Gi
```

When using this option, `image` should be an optional value.

If a user does not set the value, dspo should have a preferred image to that it deploys.

If the user has not set the value and dspo is updated, the image should update to the new preferred image.

If the user does set the value, it should  supersede any default option in the operator.
