### ISSUE TITLE
[Bug]: Using Operator v2, I cannot remove the project

### ISSUE THREAD

**Issue by diegolovison** [opendatahub-io/data-science-pipelines-operator#297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

ODH Dashboard UI

### Version

RHODS Operator 2.1.0

### Environment

NA

### Current Behavior

The project is not removed.

### Expected Behavior

Project is removed

### Steps To Reproduce

```bash
oc new-project foo-bar
```

*data-science-pipelines-sample.yaml*
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: pipelines-definition
spec:
  objectStorage:
    minio:
      # Image field is required
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
```
```bash
oc apply -f data-science-pipelines-sample.yaml
```
Using `TektonClient`, create `create_run_from_pipeline_func` for https://github.com/kubeflow/kfp-tekton/blob/master/samples/flip-coin/condition.py

Try to remove: `foo-bar`. It will be in the Terminating status forever 

### Workaround (if any)

NA

### Anything else

NA
