### ISSUE TITLE
[Bug]: APIServer with enableOauth=False still has oauth port in APIServer service 

### ISSUE THREAD

**Issue by cam-garrison** [opendatahub-io/data-science-pipelines-operator#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Standalone DSPO (without ODH)

### Version

quay.io/opendatahub/data-science-pipelines-operator:latest

### Environment

Using CRC, with latest ODH build and using DSC spec to enable DSP/create DSPO pod. 

### Current Behavior

When creating a DSPA with `.spec.apiServer.enableOauth: false`, the pipeline's service (ie service `ds-pipeline-sample` for DSPA named `sample`) still contains the oauth port:

```
spec:  
  ports:
    - name: oauth
      protocol: TCP
      port: 8443
      targetPort: oauth
``` 

### Expected Behavior

I would expect when creating a DSPA without oauth container in the APIServer pod, that the spec.ports of the service wouldn't contain the oauth port like so:

```
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: http
    - name: grpc
      protocol: TCP
      port: 8887
      targetPort: 8887
```

### Anything else

Looks like it should be fixed [here](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/internal/apiserver/service.yaml.tmpl) by using similar logic as in the [deployment](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/5dbf01264bd479591d2dfca89007b005f787b4d1/config/internal/apiserver/deployment.yaml.tmpl#L176C4-L176C4).
