### ISSUE TITLE
PR cleanup github workflow is failing 

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/data-science-pipelines-operator#83]
The pull request cleanup github workflow is failing constantly 
https://github.com/opendatahub-io/data-science-pipelines-operator/actions/workflows/pr-close-image-delete.yml
the reason seems like the env var are not passing values and showing up as Null
```
  env:
    QUAY_IMAGE_REPO: 
    PR: 82
    QUAY_ROBOT_USERNAME: 
    QUAY_ROBOT_TOKEN: 
```
